<?php
/*
Plugin Name: Remove From Admin Bar
Plugin URI:  https://developer.wordpress.org/plugins/the-basics/
Description: Remove items that you don't use from the admin bar. To prevent overflow.
Version:     1.0.0
Author:      yingling017
Author URI:  https://jasonyingling.me
License:     GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: remove-from-admin
*/

// Remove items from the admin bar
function remove_from_admin_bar($wp_admin_bar) {
    /*
     * Placing items in here will only remove them from admin bar
     * when viewing the fronte end of the site
    */
    if ( ! is_admin() ) {
        // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
    	$wp_admin_bar->remove_node('si_menu');

        // WordPress Core Items (uncomment to remove)
        $wp_admin_bar->remove_node('updates');
        $wp_admin_bar->remove_node('comments');
        $wp_admin_bar->remove_node('new-content');
        //$wp_admin_bar->remove_node('wp-logo');
        //$wp_admin_bar->remove_node('site-name');
        //$wp_admin_bar->remove_node('my-account');
        //$wp_admin_bar->remove_node('search');
        //$wp_admin_bar->remove_node('customize');
    }

    /*
     * Items placed outside the if statement will remove it from both the frontend
     * and backend of the site
    */
    $wp_admin_bar->remove_node('wp-logo');
}
add_action('admin_bar_menu', 'remove_from_admin_bar', 999);

// Clear the node titles
// This will only work if the node is using a :before element for the icon
function clear_node_title( $wp_admin_bar ) {

	$all_toolbar_nodes = $wp_admin_bar->get_nodes();
    // Create an array of node ID's we'd like to remove
    $clear_titles = array(
        'site-name',
        'customize',
    );

	foreach ( $all_toolbar_nodes as $node ) {

        // Run an if check to see if a node is in the array to clear_titles
        if ( in_array($node->id, $clear_titles) ) {
            // use the same node's properties
    		$args = $node;

    		// make the node title a blank string
    		$args->title = '';

    		// update the Toolbar node
    		$wp_admin_bar->add_node( $args );
        }
	}
}
add_action( 'admin_bar_menu', 'clear_node_title', 999 );

?>
